apiVersion: v1
kind: Service
metadata:
  labels:
    app: stats-viewer
  name: stats-viewer
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: stats-viewer
  type: ClusterIP
